[build]
target = "loongarch64-unknown-none"

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/hal/arch/loongarch/linker.ld",
    "-Cforce-frame-pointers=yes",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]